### ISSUE TITLE
Keysanity: Wave beam softlock via LN in Normal

### ISSUE THREAD

**Issue by TarThoron** [tewtal/SMZ3Randomizer#107]
In Normal, you can softlock in the Wave beam area via LN if you don't have UN2 Key. Other ways out are the wave gate in Kronic Boost or going back to the Mire portal through Lava Dive/Gold Torizo. Both ways require going through reverse Volcano room, which means travelling through lava.

**Comment by tewtal** [comment]
This doesn't seem like it's an issue since that item isn't in logic through LN as far as I can tell. The logic is as follows:
`                    
Normal => items => (items.CardNorfairL2 && (items.CanFly() || items.Morph && (items.SpeedBooster || items.CanPassBombPassages()) || items.HiJump || items.Ice)) || 
(items.SpeedBooster && items.Wave && items.Morph && items.Super),
`

**Comment by TarThoron** [comment]
Issue isn't so much with Wave/Missile, it's with everything in LN East beyond the key door (so everything but Mickey Mouse). For example, if flippers are at Fireflea, and both wave and Norfair 2 are in Swamp Palace, with grav and/or space jump beyond that, your only way out is a gate glitch or reverse Ampitheater.

**Comment by TarThoron** [comment]
Lava damage is debatable, but was the reason for https://github.com/tewtal/alttp_sm_combo_randomizer/pull/125

**Comment by tewtal** [comment]
Aha okay, but that should be an easy fix. I've added a new CanExit check on those items in LN East that checks for Norfair2 or Wave+Grav for normal, and is always true for Hard. That should fix it I think, and keep logic in Normal the same as expected.
